'use client'
import { useState, useEffect } from 'react';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import { Button } from "@/components/ui/button"

import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "@/components/ui/menubar"
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ['latin'] })

// Define metadata outside the component
const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [userRole, setUserRole] = useState('');

  useEffect(() => {
    const isLoggedIn = localStorage.getItem('isLoggedIn');
    setIsLoggedIn(isLoggedIn === 'true');
    const userRole = localStorage.getItem('Rol');
    if (userRole) {
      setUserRole(userRole);
    }
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('isLoggedIn');
    setIsLoggedIn(false);
    window.location.href = '/login';
  };

  return (
    <html lang="en">
      <head />
      <body style={{ position: 'relative' }}>
        <MenubarContainer>
          {/* Contenedor del menú */}
          <Menubar>
            {/* Menú para administradores */}
            {isLoggedIn && userRole === 'Administrador' && (
              <MenubarMenu>
                <a href="/users">
                  <MenubarTrigger>Usuarios</MenubarTrigger>
                </a>
              </MenubarMenu>
            )}
            {isLoggedIn && userRole === 'Administrador' && (
              <MenubarMenu>
                <MenubarTrigger>Pedidos</MenubarTrigger>
                <MenubarContent>
                  <a href="/orders">
                    <MenubarItem>Lista de pedidos</MenubarItem>
                  </a>
                  <MenubarSeparator />
                  <a href="/orders/new-order">
                    <MenubarItem>Nuevo Pedido</MenubarItem>
                  </a>
                </MenubarContent>
              </MenubarMenu>
            )}
            {/* Menú para usuarios autenticados */}
            {isLoggedIn && userRole === 'Administrador' && (
              <MenubarMenu>
                <MenubarTrigger>Entregas</MenubarTrigger>
                <MenubarContent>
                  <a href="/deliveries">
                    <MenubarItem>Lista de entregas</MenubarItem>
                  </a>
                  <MenubarSeparator />
                  <a href="/deliveries/new-delivery">
                    <MenubarItem>Gestionar entregas</MenubarItem>
                  </a>
                </MenubarContent>
              </MenubarMenu>
            )}
            {/* Menú para todos los usuarios autenticados */}
            {isLoggedIn && (
              <MenubarMenu>
                <MenubarTrigger>Devoluciones</MenubarTrigger>
                <MenubarContent>
                  {userRole === 'Administrador' && (
                    <a href="/returns">
                      <MenubarItem>Devoluciones</MenubarItem>
                    </a>
                  )}
                  <MenubarSeparator />
                  <a href="/returns/new-return">
                    <MenubarItem>Nueva Devolución</MenubarItem>
                  </a>
                </MenubarContent>
              </MenubarMenu>
            )}
            {isLoggedIn && userRole === 'Administrador' && (
              <MenubarMenu>
                <MenubarTrigger>Stock</MenubarTrigger>
                <MenubarContent>
                  <a href="/stock">
                    <MenubarItem>Stock Material</MenubarItem>
                  </a>
                  <MenubarSeparator />
                  <a href="/resume">
                    <MenubarItem>Resumen</MenubarItem>
                  </a>
                </MenubarContent>
              </MenubarMenu>
            )}

          </Menubar>
        </MenubarContainer>

        {/* Contenedor del botón de cerrar sesión */}
        <div style={{ position: 'absolute', top: '1rem', right: '1rem' }}>
          {isLoggedIn && (
            <Button onClick={handleLogout}>Cerrar sesión</Button>
          )}
        </div>

        {/* Contenido principal */}
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}

const MenubarContainer = ({ children }: { children: React.ReactNode }) => (
  <header style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '4rem', maxWidth: '800px', margin: '0 auto' }}>
    {children}
  </header>
);
